steps:
  - name: 'maven'
    entrypoint: 'mvn'
    args: ['clean', 'install', '-DskipTests']
  #https://cloud.google.com/build/docs/cloud-builders
  # Build the container image
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/$PROJECT_ID/github.com/ramyamagesh10734605/spring-boot:$COMMIT_SHA', '.']
  # Push the container image to Container Registry
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/github.com/ramyamagesh10734605/spring-boot:$COMMIT_SHA']
  # Deploy container image to Cloud Run
  #- name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
  # entrypoint: gcloud
  #  args:
  #    - 'run'
  #    - 'deploy'
  #    - '$_SERVICE_NAME'
  #    - '--image'
  #    - 'gcr.io/$PROJECT_ID/$_SERVICE_NAME:$COMMIT_SHA'
  #    - '--region'
  #    - '$_DEPLOY_REGION'
  - name: 'gcr.io/cloud-builders/gke-deploy'
    args:
     - run
     - --filename=./deployment.yaml
     - --image=gcr.io/$PROJECT_ID/github.com/ramyamagesh10734605/spring-boot:$COMMIT_SHA
     - --location=us-central1-c
     - --cluster=cluster-1
     
options:
  logging: CLOUD_LOGGING_ONLY

images: [gcr.io/$PROJECT_ID/$_SERVICE_NAME:$COMMIT_SHA]